# Generated by Django 5.0.8 on 2024-08-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0004_alter_recruitment_compensation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='recruitment_id',
            new_name='recruitment',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='user',
        ),
    ]
