# Generated by Django 5.0.8 on 2024-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0005_rename_company_id_recruitment_company_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('user', 'recruitment'), name='unique_user_recruitment'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='recruitment',
            table='recruitment',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
