# Generated by Django 5.0.8 on 2024-08-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0006_resume_unique_user_recruitment_alter_company_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recruitment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='resume',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
