# Generated by Django 5.0.8 on 2024-08-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0007_alter_company_table_alter_recruitment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='recruitment',
            table='recruitment',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
